# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'birthdayframe.ui'
#
# Created: Sat Jul 27 07:04:18 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BirthdayFrame(object):
    def setupUi(self, BirthdayFrame):
        BirthdayFrame.setObjectName(_fromUtf8("BirthdayFrame"))
        BirthdayFrame.resize(562, 373)
        BirthdayFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        BirthdayFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(BirthdayFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_8 = QtGui.QGroupBox(BirthdayFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.edit_time1 = QtGui.QLineEdit(self.groupBox_4)
        self.edit_time1.setEnabled(False)
        self.edit_time1.setMinimumSize(QtCore.QSize(140, 0))
        self.edit_time1.setMaxLength(20)
        self.edit_time1.setObjectName(_fromUtf8("edit_time1"))
        self.gridLayout_2.addWidget(self.edit_time1, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.edit_time2 = QtGui.QLineEdit(self.groupBox_4)
        self.edit_time2.setEnabled(False)
        self.edit_time2.setMinimumSize(QtCore.QSize(140, 0))
        self.edit_time2.setMaxLength(20)
        self.edit_time2.setObjectName(_fromUtf8("edit_time2"))
        self.gridLayout_2.addWidget(self.edit_time2, 1, 1, 1, 1)
        self.edit_time3 = QtGui.QLineEdit(self.groupBox_4)
        self.edit_time3.setEnabled(False)
        self.edit_time3.setMinimumSize(QtCore.QSize(140, 0))
        self.edit_time3.setMaxLength(20)
        self.edit_time3.setObjectName(_fromUtf8("edit_time3"))
        self.gridLayout_2.addWidget(self.edit_time3, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radio_lu = QtGui.QRadioButton(self.groupBox_5)
        self.radio_lu.setChecked(True)
        self.radio_lu.setObjectName(_fromUtf8("radio_lu"))
        self.gridLayout_3.addWidget(self.radio_lu, 0, 0, 1, 1)
        self.radio_ll = QtGui.QRadioButton(self.groupBox_5)
        self.radio_ll.setObjectName(_fromUtf8("radio_ll"))
        self.gridLayout_3.addWidget(self.radio_ll, 1, 0, 1, 1)
        self.radio_lc = QtGui.QRadioButton(self.groupBox_5)
        self.radio_lc.setObjectName(_fromUtf8("radio_lc"))
        self.gridLayout_3.addWidget(self.radio_lc, 2, 0, 1, 1)
        self.combo_p = QtGui.QComboBox(self.groupBox_5)
        self.combo_p.setEnabled(False)
        self.combo_p.setObjectName(_fromUtf8("combo_p"))
        self.gridLayout_3.addWidget(self.combo_p, 2, 1, 1, 1)
        self.combo_c = QtGui.QComboBox(self.groupBox_5)
        self.combo_c.setEnabled(False)
        self.combo_c.setObjectName(_fromUtf8("combo_c"))
        self.gridLayout_3.addWidget(self.combo_c, 3, 1, 1, 1)
        self.edit_lon = QtGui.QLineEdit(self.groupBox_5)
        self.edit_lon.setEnabled(False)
        self.edit_lon.setObjectName(_fromUtf8("edit_lon"))
        self.gridLayout_3.addWidget(self.edit_lon, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.gridLayout.addWidget(self.groupBox_8, 1, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(BirthdayFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radio_male = QtGui.QRadioButton(self.groupBox)
        self.radio_male.setChecked(True)
        self.radio_male.setObjectName(_fromUtf8("radio_male"))
        self.horizontalLayout.addWidget(self.radio_male)
        self.radio_female = QtGui.QRadioButton(self.groupBox)
        self.radio_female.setObjectName(_fromUtf8("radio_female"))
        self.horizontalLayout.addWidget(self.radio_female)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.time = QtGui.QTimeEdit(self.groupBox_2)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setTime(QtCore.QTime(12, 0, 0))
        self.time.setObjectName(_fromUtf8("time"))
        self.gridLayout_4.addWidget(self.time, 1, 0, 1, 1)
        self.btnNow = QtGui.QPushButton(self.groupBox_2)
        self.btnNow.setDefault(True)
        self.btnNow.setObjectName(_fromUtf8("btnNow"))
        self.gridLayout_4.addWidget(self.btnNow, 1, 1, 1, 1)
        self.calendar = QtGui.QCalendarWidget(self.groupBox_2)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.gridLayout_4.addWidget(self.calendar, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(BirthdayFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.edit_name = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.edit_name.sizePolicy().hasHeightForWidth())
        self.edit_name.setSizePolicy(sizePolicy)
        self.edit_name.setObjectName(_fromUtf8("edit_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edit_name)
        self.gridLayout.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(BirthdayFrame)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAdd = QtGui.QPushButton(self.groupBox_3)
        self.btnAdd.setEnabled(False)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnUpdate = QtGui.QPushButton(self.groupBox_3)
        self.btnUpdate.setEnabled(False)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.horizontalLayout_2.addWidget(self.btnUpdate)
        self.btnDelete = QtGui.QPushButton(self.groupBox_3)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.label_2.setBuddy(self.edit_time1)
        self.label_3.setBuddy(self.edit_time2)
        self.label_4.setBuddy(self.edit_time3)
        self.label.setBuddy(self.edit_name)

        self.retranslateUi(BirthdayFrame)
        QtCore.QObject.connect(self.btnAdd, QtCore.SIGNAL(_fromUtf8("clicked()")), BirthdayFrame.onBtnAdd)
        QtCore.QObject.connect(self.time, QtCore.SIGNAL(_fromUtf8("timeChanged(QTime)")), BirthdayFrame.onTimeChg)
        QtCore.QObject.connect(self.calendar, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), BirthdayFrame.onDateChg)
        QtCore.QObject.connect(self.radio_male, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BirthdayFrame.onGenderToggled)
        QtCore.QObject.connect(self.radio_female, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BirthdayFrame.onGenderToggled)
        QtCore.QObject.connect(self.edit_name, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BirthdayFrame.onNameChg)
        QtCore.QObject.connect(self.btnNow, QtCore.SIGNAL(_fromUtf8("clicked()")), BirthdayFrame.onBtnNow)
        QtCore.QObject.connect(self.radio_lu, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BirthdayFrame.onLocToggled)
        QtCore.QObject.connect(self.radio_ll, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BirthdayFrame.onLocToggled)
        QtCore.QObject.connect(self.radio_lc, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BirthdayFrame.onLocToggled)
        QtCore.QObject.connect(self.combo_p, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), BirthdayFrame.onProvinceChg)
        QtCore.QObject.connect(self.combo_c, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), BirthdayFrame.onCityChg)
        QtCore.QObject.connect(self.edit_lon, QtCore.SIGNAL(_fromUtf8("editingFinished()")), BirthdayFrame.onEditLonFinish)
        QtCore.QObject.connect(self.btnUpdate, QtCore.SIGNAL(_fromUtf8("clicked()")), BirthdayFrame.onBtnUpdate)
        QtCore.QObject.connect(self.btnDelete, QtCore.SIGNAL(_fromUtf8("clicked()")), BirthdayFrame.onBtnDelete)
        QtCore.QMetaObject.connectSlotsByName(BirthdayFrame)
        BirthdayFrame.setTabOrder(self.edit_name, self.radio_male)
        BirthdayFrame.setTabOrder(self.radio_male, self.radio_female)
        BirthdayFrame.setTabOrder(self.radio_female, self.calendar)
        BirthdayFrame.setTabOrder(self.calendar, self.time)
        BirthdayFrame.setTabOrder(self.time, self.radio_lu)
        BirthdayFrame.setTabOrder(self.radio_lu, self.radio_ll)
        BirthdayFrame.setTabOrder(self.radio_ll, self.edit_lon)
        BirthdayFrame.setTabOrder(self.edit_lon, self.radio_lc)
        BirthdayFrame.setTabOrder(self.radio_lc, self.combo_p)
        BirthdayFrame.setTabOrder(self.combo_p, self.combo_c)
        BirthdayFrame.setTabOrder(self.combo_c, self.btnAdd)
        BirthdayFrame.setTabOrder(self.btnAdd, self.edit_time1)
        BirthdayFrame.setTabOrder(self.edit_time1, self.edit_time2)
        BirthdayFrame.setTabOrder(self.edit_time2, self.edit_time3)

    def retranslateUi(self, BirthdayFrame):
        BirthdayFrame.setWindowTitle(_translate("BirthdayFrame", "Frame", None))
        self.groupBox_4.setTitle(_translate("BirthdayFrame", "时间修正", None))
        self.label_2.setText(_translate("BirthdayFrame", "手表时", None))
        self.label_3.setText(_translate("BirthdayFrame", "平太阳时", None))
        self.label_4.setText(_translate("BirthdayFrame", "真太阳时", None))
        self.groupBox_5.setTitle(_translate("BirthdayFrame", "出生地", None))
        self.radio_lu.setText(_translate("BirthdayFrame", "未知", None))
        self.radio_ll.setText(_translate("BirthdayFrame", "经度", None))
        self.radio_lc.setText(_translate("BirthdayFrame", "城市", None))
        self.edit_lon.setText(_translate("BirthdayFrame", "120.0", None))
        self.groupBox.setTitle(_translate("BirthdayFrame", "性别", None))
        self.radio_male.setText(_translate("BirthdayFrame", "男", None))
        self.radio_female.setText(_translate("BirthdayFrame", "女", None))
        self.groupBox_2.setTitle(_translate("BirthdayFrame", "生日", None))
        self.time.setDisplayFormat(_translate("BirthdayFrame", "hh:mm:ss", None))
        self.btnNow.setText(_translate("BirthdayFrame", "当前时间", None))
        self.label.setText(_translate("BirthdayFrame", "姓名", None))
        self.btnAdd.setText(_translate("BirthdayFrame", "新增记录", None))
        self.btnUpdate.setText(_translate("BirthdayFrame", "更新记录", None))
        self.btnDelete.setText(_translate("BirthdayFrame", "删除记录", None))

